% Copyright (c) 2025 - for information on the respective copyright owner 
% see the NOTICE file or the repository <https://github.com/boschglobal/audi-image>
%
% SPDX-License-Identifier: Apache-2.0

% -------------------------------------------------------------------------
% Process frames for movie with composed image
% -------------------------------------------------------------------------
% Open SAI results file and generate frames for a movie with composed image

function ProcessFramesForMovieWithComposedImage( ...
    fullFilenameOfSaiMatFile, ...
    fullFilenameOfMovieCochleagramMatFile, ...
    fullFilenameOfMoviePitchogramMatFile, ...
    fullFolderForSaiFramesOfAudioFile, ...
    namePatternForSaiFrames, ...
    options ...
    )
    COLORMAP_SCALE_FACTOR = 1.3;
    COLORMAP_SCALE_FACTOR_FOR_SAI = 32;
    COLORMAP_SCALE_FACTOR_FOR_COCHLEAGRAM = 7;
    COLORMAP_SCALE_FACTOR_FOR_PITCHOGRAM = 8.5;
    
    load(fullFilenameOfSaiMatFile, ...
        'totalNumberOfSegments', ...
        'totalWidthOfAllLayers', ...
        'stabilizedAuditoryImage' ...
        )
    load(fullFilenameOfMovieCochleagramMatFile, ...
        'cochleagramFromSaiMovie' ...
        )
    load(fullFilenameOfMoviePitchogramMatFile, ...
        'pitchogramFromSaiMovie' ...
        )

    colormapMatrix = ReturnColormapMatrix(options.NAME_OF_COLORMAP);
    borderForComposedImage = ones(2, totalWidthOfAllLayers);
    
    h = waitbar(0,['1 / ' num2str(totalNumberOfSegments)],'Name','Segment processing in progress...');
    for numberOfActualSegment = 1:totalNumberOfSegments
        waitbar(numberOfActualSegment/totalNumberOfSegments,h,[num2str(numberOfActualSegment) ' / ' num2str(totalNumberOfSegments)])
        actualFrameOfSaiMovie = [ ...
            COLORMAP_SCALE_FACTOR_FOR_COCHLEAGRAM * cochleagramFromSaiMovie(:,ceil(((end+1):(2*end))/2),numberOfActualSegment); ...    % default 4 * 
            borderForComposedImage; ...
            stabilizedAuditoryImage(ceil((1:(2*end))/2),:,numberOfActualSegment); ...
            borderForComposedImage; ...
            COLORMAP_SCALE_FACTOR_FOR_PITCHOGRAM * max(0,pitchogramFromSaiMovie(:,:,numberOfActualSegment)) ...
            ];

        imwrite( ...
            COLORMAP_SCALE_FACTOR * COLORMAP_SCALE_FACTOR_FOR_SAI * actualFrameOfSaiMovie, ...
            colormapMatrix, ...
            fullfile(fullFolderForSaiFramesOfAudioFile,sprintf(namePatternForSaiFrames, numberOfActualSegment)) ...
            );
    end
    close(h)
end